name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t your-docker-username/your-image-name:latest -f my-docker-project/Dockerfile .
        docker tag your-docker-username/your-image-name:latest your-docker-username/your-image-name:latest

    - name: Push Docker image
      run: docker push your-docker-username/your-image-name:latest
